services:
  db:
    image: postgres:16.5
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: .env
    ports:
      - "5432:5432" # for dev only
    environment:
      - POSTGRES_USER=$SQL_USER
      - POSTGRES_PASSWORD=$SQL_PASSWORD
      - POSTGRES_DB=$SQL_DATABASE

  web:
    build:
      context: .
      dockerfile: ./deployment/Dockerfile
    container_name: canteen_ms
    image: canteen-django:dev
    env_file: .env
    ports:
      - "8000:8000"
    command:
      - /scripts/start-django-dev.sh
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_started
    develop:
      watch:
        - action: sync
          path: ./apps
          target: /app/apps

        - action: sync
          path: ./config
          target: /app/config

        - action: rebuild
          path: ./uv.lock

        - action: rebuild
          path: ./pyproject.toml

        - action: rebuild
          path: ./deployment/Dockerfile

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  postgres_data:
